### ISSUE TITLE
Glade

### ISSUE THREAD

**Issue by R3D9477** [StefanSalewski/oldgtk3#1]
Hi. Can I use GtkBuilder & Glade in Nim via this library?

**Comment by StefanSalewski** [comment]
EDIT: Oh, I just noticed that I was replying to an gintro issue, while you asked indeed about oldGTK3. For oldGTK3 sure, NEd uses it. But you may consider new gintro, which got simple nimble install some days ago. And works for Windows too, as user zetashift said. 

--
This is for gintro...

Yes, that should work. But currently I do not provide an example.

My  NEd Nim editor, which uses oldGTK3 nimble package, is using  GtkBuilder & Glade, so you may look at its source code to get an idea.

I myself have never used GtkBuilder & Glade that much. So providing an example has not high priority for me currently, and I have not much spare time now.

Have you ever used GtkBuilder & Glade before from other languages? I had the feeling that starting using it is not that easy, and documentation is not too great. If you intend to create a larger project with it, then I may consider giving it a higher priority.

**Comment by R3D9477** [comment]
@StefanSalewski Thanks for hint!
