### ISSUE TITLE
DEPRECATED enum value in gobject.nim "Error: invalid order in enum 'DEPRECATED'" 32b OS

### ISSUE THREAD

**Issue by Wh1teDuke** [StefanSalewski/oldgtk3#2]
https://github.com/StefanSalewski/oldgtk3/blob/f74e36abe7a51993bfa75bffba8a385fa56cafb7/oldgtk3/gobject.nim#L641

Because the enum has size:cint, is not possible to compile in 32b.
Apparently, the order is stored in int32, which makes the result a negative.

https://github.com/StefanSalewski/oldgtk3/blob/f74e36abe7a51993bfa75bffba8a385fa56cafb7/oldgtk3/gobject.nim#L636

 Shall `DEPRECATED` be removed?

**Comment by StefanSalewski** [comment]
Thanks for reporting.

So I assume that gintro does not work on 32 bit systems too, I always wondered if someone had tested gintro on a 32 bit system.

But I wonder why you report the issue for the oldgtk3 issue tracker, I don't think that you intent to use the oldgtk3 package directly?

Finally above issue is closely related to c2nim, as oldgtk3 was generated based on c2nim, so maybe I should ask Araq. And when I would fix this single issue, dozen more may pop up on 32 bit systems, which I can not test for, as I do not intent to buy a 32 bit box soon.

So generates this issue some trouble for you, or are you only checking random nimble packages for 32 bit compile?

**Comment by Wh1teDuke** [comment]
> But I wonder why you report the issue for the oldgtk3 issue tracker, I don't think that you intent to use the oldgtk3 package directly?

Yes I do



> So generates this issue some trouble for you

It doesn't since I commented that line, everything seems to work as expected.

> or are you only checking random nimble packages for 32 bit compile?

No, I'm not that superhero. But I'm actually checking for some GUI that works for me.

**Comment by StefanSalewski** [comment]
That is interesting. I was going to remove oldgtk3 as no one has used it in the last five years. As you may know I use it for gintro install, at least the gir, glib and gobject modules, and some people do not like that, they suggested that I copy these 3 modules into the gintro nimble package instead.

If there is really only this single issue in oldgtk3 then I will fix it, maybe then gintro install will work for 32 bit systems.

And the final question: Why do you not use gintro instead? I wrote my Ned editor with oldgtk3 five years ago, and I can say that using gtk low level bindings with Nim is a pain. I would prefer using C directly them.

**Comment by Wh1teDuke** [comment]
> That is interesting. I was going to remove oldgtk3 as no one has used it in the last five years. As you may know I use it for gintro

I want to be the one who breaks the curse.

> And the final question: Why do you not use gintro instead?

I think I tried doing that but there was some error during the installation, maybe this very issue?

> and I can say that using gtk low level bindings with Nim is a pain. I would prefer using C directly them.

I know, actually I'm coding a high level wrapper around it, higher than gintro. This is a small sneak peak:


```nim
# e11.nim: ADVANCED window example

import std/random
import ngui


proc main =
  # ALWAYS start with app()
  let app = app()
  let window = window("e11: ADVANCED Window")
  let bRandom = button("Random position")
  
  bRandom.onClickDo:    
    window.position =
      (x: 500 + (rand(-100 .. +100)), y: 500 + (rand(-100 .. +100)))
  
  # Window will create a new VBox behind the curtain for you
  # This is because under some implementations (gtk3) a window can only
  # hold 1 element
  window.add(label("Advanced stuff here"), bRandom)

  app.add(window)
  
  doAssert app.window == window
  doAssert app.head == window
  doAssert app.head == app.tail
  
  # NEVER add new elements to app after run()
  run(app)

main()
```

**Comment by StefanSalewski** [comment]
>I think I tried doing that but there was some error during the installation, maybe this very issue?

Sure, as gobject, glib and gir from oldgtk3 are used for bootstrapping gintro.

>I know, actually I'm coding a high level wrapper around it, higher than gintro.

The problem is that updating oldgtk3 for GTK4 is nearly impossible unfortunately. Oldgtk3 uses Ruby scripts for the bindings generation, so it was intended to make updating possible. But I did three updates, starting at GTK3.12 and it was a large and boring task, I spent 600 hours totally on oldgtk3 and my fear is that I will only do small fixes and never are real update on it again, sorry.

**Comment by Wh1teDuke** [comment]
Don't worry, if fixing this issue makes gintro usable for me, I'll switch to it then.

**Comment by StefanSalewski** [comment]
It is a strange and hard issue, so I have to consult the Nim core devs:

https://github.com/nim-lang/Nim/issues/16926

Maybe you can test if the suggested solution with

```
type
  GParamFlags* {.size: sizeof(cint), pure.} = enum
    G_PARAM_DEPRECATED = (1.cint shl 31)
    G_PARAM_READABLE = 1 shl 0, G_PARAM_WRITABLE = 1 shl 1,
```

compiles and works on 32 bit.

**Comment by Wh1teDuke** [comment]
> It is a strange and hard issue, so I have to consult the Nim core devs:
> 
> [nim-lang/Nim#16926](https://github.com/nim-lang/Nim/issues/16926)
> 
> Maybe you can test if the suggested solution with
> 
> ```
> type
>   GParamFlags* {.size: sizeof(cint), pure.} = enum
>     G_PARAM_DEPRECATED = (1.cint shl 31)
>     G_PARAM_READABLE = 1 shl 0, G_PARAM_WRITABLE = 1 shl 1,
> ```
> 
> compiles and works on 32 bit.

Hello, I tried your suggestion, but sadly I get the same error. And with cuint:
`Error: unhandled exception: value out of range: 2147483648 notin -2147483648 .. 2147483647 [RangeDefect]`

**Comment by StefanSalewski** [comment]
Thanks for testing. I hesitate to use your suggestion from the PR with distinct cint, as maybe someone other is using the module and that would be a larger change, and because it would be inconsistent with all the other enums then. And finally this bug should be really fixed in the compiler.

**Comment by Wh1teDuke** [comment]
> Thanks for testing. I hesitate to use your suggestion from the PR with distinct cint, as maybe someone other is using the module and that would be a larger change, and because it would be inconsistent with all the other enums then. And finally this bug should be really fixed in the compiler.

Ok, I understand it. You may revive the PR if you change your mind, and thanks for your help.

**Comment by StefanSalewski** [comment]
Can you test mratsims uint32 suggestion?

https://forum.nim-lang.org/t/7490

**Comment by Wh1teDuke** [comment]
> Can you test mratsims uint32 suggestion?
> 
> https://forum.nim-lang.org/t/7490

Hello there, glad you are still thinking about the issue. And yes, the code compiles, this fixes the issue. Maybe the first time I forgot to change the order of the enum? Anyway, thanks for solving my problem.

**Comment by StefanSalewski** [comment]
I have just pushed the best currently possible fix to github.

```
$ grep -A9 "ParamFlags\*" gobject.nim 
#  GParamFlags* {.size: sizeof(cint), pure.} = enum
#    READABLE = 1 shl 0, WRITABLE = 1 shl 1,
#    CONSTRUCT = 1 shl 2, CONSTRUCT_ONLY = 1 shl 3,
#    LAX_VALIDATION = 1 shl 4, STATIC_NAME = 1 shl 5,
#    STATIC_NICK = 1 shl 6, STATIC_BLURB = 1 shl 7,
#    EXPLICIT_NOTIFY = 1 shl 30, DEPRECATED = 1 shl 31

# see https://forum.nim-lang.org/t/7490#47510
# see https://github.com/nim-lang/Nim/issues/16926
# see https://github.com/StefanSalewski/oldgtk3/issues/2
--
  GParamFlags* {.size: sizeof(cint), pure.} = enum
    DEPRECATED = (1.cint shl 31)
    READABLE = 1 shl 0, WRITABLE = 1 shl 1,
    CONSTRUCT = 1 shl 2, CONSTRUCT_ONLY = 1 shl 3,
    LAX_VALIDATION = 1 shl 4, STATIC_NAME = 1 shl 5,
    STATIC_NICK = 1 shl 6, STATIC_BLURB = 1 shl 7,
    EXPLICIT_NOTIFY = 1 shl 30
```

If there should still be issues please ask on the Nim forum or post an issue on the Nim github issue tracker.

Gintro v0.8.6 is available also now!
